### ISSUE TITLE
How to get SECRET_KEY, SALT and IV?

### ISSUE THREAD

**Issue by donenoyes** [JoshLudahl/Tokenator#3]
While compiling the app, it crashes as there is no SECRET_KEY, SALT and IV provided.

```
  buildConfigField("String", "SECRET_KEY", "\"${getProperty("SECRET_KEY")}\"")
  buildConfigField("String", "SALT", "\"${getProperty("SALT")}\"")
  buildConfigField("String", "IV", "\"${getProperty("IV")}\"")
```

Where to find these keys and please add instructions on how to compile the app if some more configuration is required.

**Comment by JoshLudahl** [comment]
Hello.  I will add how to set these when I have a chance this weekend.

Cheers
